// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/telagod/subme/ent/modelpriceoverride"
	"github.com/telagod/subme/ent/predicate"
)

// ModelPriceOverrideUpdate is the builder for updating ModelPriceOverride entities.
type ModelPriceOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPriceOverrideMutation
}

// Where appends a list predicates to the ModelPriceOverrideUpdate builder.
func (_u *ModelPriceOverrideUpdate) Where(ps ...predicate.ModelPriceOverride) *ModelPriceOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelPriceOverrideUpdate) SetModelID(v string) *ModelPriceOverrideUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableModelID(v *string) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetPinnedProviderTag sets the "pinned_provider_tag" field.
func (_u *ModelPriceOverrideUpdate) SetPinnedProviderTag(v string) *ModelPriceOverrideUpdate {
	_u.mutation.SetPinnedProviderTag(v)
	return _u
}

// SetNillablePinnedProviderTag sets the "pinned_provider_tag" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillablePinnedProviderTag(v *string) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetPinnedProviderTag(*v)
	}
	return _u
}

// ClearPinnedProviderTag clears the value of the "pinned_provider_tag" field.
func (_u *ModelPriceOverrideUpdate) ClearPinnedProviderTag() *ModelPriceOverrideUpdate {
	_u.mutation.ClearPinnedProviderTag()
	return _u
}

// SetManualInput sets the "manual_input" field.
func (_u *ModelPriceOverrideUpdate) SetManualInput(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.ResetManualInput()
	_u.mutation.SetManualInput(v)
	return _u
}

// SetNillableManualInput sets the "manual_input" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableManualInput(v *float64) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetManualInput(*v)
	}
	return _u
}

// AddManualInput adds value to the "manual_input" field.
func (_u *ModelPriceOverrideUpdate) AddManualInput(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.AddManualInput(v)
	return _u
}

// ClearManualInput clears the value of the "manual_input" field.
func (_u *ModelPriceOverrideUpdate) ClearManualInput() *ModelPriceOverrideUpdate {
	_u.mutation.ClearManualInput()
	return _u
}

// SetManualOutput sets the "manual_output" field.
func (_u *ModelPriceOverrideUpdate) SetManualOutput(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.ResetManualOutput()
	_u.mutation.SetManualOutput(v)
	return _u
}

// SetNillableManualOutput sets the "manual_output" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableManualOutput(v *float64) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetManualOutput(*v)
	}
	return _u
}

// AddManualOutput adds value to the "manual_output" field.
func (_u *ModelPriceOverrideUpdate) AddManualOutput(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.AddManualOutput(v)
	return _u
}

// ClearManualOutput clears the value of the "manual_output" field.
func (_u *ModelPriceOverrideUpdate) ClearManualOutput() *ModelPriceOverrideUpdate {
	_u.mutation.ClearManualOutput()
	return _u
}

// SetManualCacheRead sets the "manual_cache_read" field.
func (_u *ModelPriceOverrideUpdate) SetManualCacheRead(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.ResetManualCacheRead()
	_u.mutation.SetManualCacheRead(v)
	return _u
}

// SetNillableManualCacheRead sets the "manual_cache_read" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableManualCacheRead(v *float64) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetManualCacheRead(*v)
	}
	return _u
}

// AddManualCacheRead adds value to the "manual_cache_read" field.
func (_u *ModelPriceOverrideUpdate) AddManualCacheRead(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.AddManualCacheRead(v)
	return _u
}

// ClearManualCacheRead clears the value of the "manual_cache_read" field.
func (_u *ModelPriceOverrideUpdate) ClearManualCacheRead() *ModelPriceOverrideUpdate {
	_u.mutation.ClearManualCacheRead()
	return _u
}

// SetManualCacheWrite sets the "manual_cache_write" field.
func (_u *ModelPriceOverrideUpdate) SetManualCacheWrite(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.ResetManualCacheWrite()
	_u.mutation.SetManualCacheWrite(v)
	return _u
}

// SetNillableManualCacheWrite sets the "manual_cache_write" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableManualCacheWrite(v *float64) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetManualCacheWrite(*v)
	}
	return _u
}

// AddManualCacheWrite adds value to the "manual_cache_write" field.
func (_u *ModelPriceOverrideUpdate) AddManualCacheWrite(v float64) *ModelPriceOverrideUpdate {
	_u.mutation.AddManualCacheWrite(v)
	return _u
}

// ClearManualCacheWrite clears the value of the "manual_cache_write" field.
func (_u *ModelPriceOverrideUpdate) ClearManualCacheWrite() *ModelPriceOverrideUpdate {
	_u.mutation.ClearManualCacheWrite()
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPriceOverrideUpdate) SetNote(v string) *ModelPriceOverrideUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableNote(v *string) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ModelPriceOverrideUpdate) ClearNote() *ModelPriceOverrideUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ModelPriceOverrideUpdate) SetUpdatedBy(v int64) *ModelPriceOverrideUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableUpdatedBy(v *int64) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ModelPriceOverrideUpdate) AddUpdatedBy(v int64) *ModelPriceOverrideUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ModelPriceOverrideUpdate) ClearUpdatedBy() *ModelPriceOverrideUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ModelPriceOverrideUpdate) SetCreatedAt(v time.Time) *ModelPriceOverrideUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableCreatedAt(v *time.Time) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPriceOverrideUpdate) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelPriceOverrideMutation object of the builder.
func (_u *ModelPriceOverrideUpdate) Mutation() *ModelPriceOverrideMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPriceOverrideUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPriceOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPriceOverrideUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpriceoverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPriceOverrideUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelpriceoverride.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PinnedProviderTag(); ok {
		if err := modelpriceoverride.PinnedProviderTagValidator(v); err != nil {
			return &ValidationError{Name: "pinned_provider_tag", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.pinned_provider_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := modelpriceoverride.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.note": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPriceOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpriceoverride.Table, modelpriceoverride.Columns, sqlgraph.NewFieldSpec(modelpriceoverride.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelpriceoverride.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PinnedProviderTag(); ok {
		_spec.SetField(modelpriceoverride.FieldPinnedProviderTag, field.TypeString, value)
	}
	if _u.mutation.PinnedProviderTagCleared() {
		_spec.ClearField(modelpriceoverride.FieldPinnedProviderTag, field.TypeString)
	}
	if value, ok := _u.mutation.ManualInput(); ok {
		_spec.SetField(modelpriceoverride.FieldManualInput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualInput(); ok {
		_spec.AddField(modelpriceoverride.FieldManualInput, field.TypeFloat64, value)
	}
	if _u.mutation.ManualInputCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualInput, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualOutput(); ok {
		_spec.SetField(modelpriceoverride.FieldManualOutput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualOutput(); ok {
		_spec.AddField(modelpriceoverride.FieldManualOutput, field.TypeFloat64, value)
	}
	if _u.mutation.ManualOutputCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualOutput, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualCacheRead(); ok {
		_spec.SetField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualCacheRead(); ok {
		_spec.AddField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64, value)
	}
	if _u.mutation.ManualCacheReadCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualCacheWrite(); ok {
		_spec.SetField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualCacheWrite(); ok {
		_spec.AddField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64, value)
	}
	if _u.mutation.ManualCacheWriteCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpriceoverride.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(modelpriceoverride.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpriceoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPriceOverrideUpdateOne is the builder for updating a single ModelPriceOverride entity.
type ModelPriceOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPriceOverrideMutation
}

// SetModelID sets the "model_id" field.
func (_u *ModelPriceOverrideUpdateOne) SetModelID(v string) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableModelID(v *string) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetPinnedProviderTag sets the "pinned_provider_tag" field.
func (_u *ModelPriceOverrideUpdateOne) SetPinnedProviderTag(v string) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetPinnedProviderTag(v)
	return _u
}

// SetNillablePinnedProviderTag sets the "pinned_provider_tag" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillablePinnedProviderTag(v *string) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetPinnedProviderTag(*v)
	}
	return _u
}

// ClearPinnedProviderTag clears the value of the "pinned_provider_tag" field.
func (_u *ModelPriceOverrideUpdateOne) ClearPinnedProviderTag() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearPinnedProviderTag()
	return _u
}

// SetManualInput sets the "manual_input" field.
func (_u *ModelPriceOverrideUpdateOne) SetManualInput(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.ResetManualInput()
	_u.mutation.SetManualInput(v)
	return _u
}

// SetNillableManualInput sets the "manual_input" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableManualInput(v *float64) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetManualInput(*v)
	}
	return _u
}

// AddManualInput adds value to the "manual_input" field.
func (_u *ModelPriceOverrideUpdateOne) AddManualInput(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.AddManualInput(v)
	return _u
}

// ClearManualInput clears the value of the "manual_input" field.
func (_u *ModelPriceOverrideUpdateOne) ClearManualInput() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearManualInput()
	return _u
}

// SetManualOutput sets the "manual_output" field.
func (_u *ModelPriceOverrideUpdateOne) SetManualOutput(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.ResetManualOutput()
	_u.mutation.SetManualOutput(v)
	return _u
}

// SetNillableManualOutput sets the "manual_output" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableManualOutput(v *float64) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetManualOutput(*v)
	}
	return _u
}

// AddManualOutput adds value to the "manual_output" field.
func (_u *ModelPriceOverrideUpdateOne) AddManualOutput(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.AddManualOutput(v)
	return _u
}

// ClearManualOutput clears the value of the "manual_output" field.
func (_u *ModelPriceOverrideUpdateOne) ClearManualOutput() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearManualOutput()
	return _u
}

// SetManualCacheRead sets the "manual_cache_read" field.
func (_u *ModelPriceOverrideUpdateOne) SetManualCacheRead(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.ResetManualCacheRead()
	_u.mutation.SetManualCacheRead(v)
	return _u
}

// SetNillableManualCacheRead sets the "manual_cache_read" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableManualCacheRead(v *float64) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetManualCacheRead(*v)
	}
	return _u
}

// AddManualCacheRead adds value to the "manual_cache_read" field.
func (_u *ModelPriceOverrideUpdateOne) AddManualCacheRead(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.AddManualCacheRead(v)
	return _u
}

// ClearManualCacheRead clears the value of the "manual_cache_read" field.
func (_u *ModelPriceOverrideUpdateOne) ClearManualCacheRead() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearManualCacheRead()
	return _u
}

// SetManualCacheWrite sets the "manual_cache_write" field.
func (_u *ModelPriceOverrideUpdateOne) SetManualCacheWrite(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.ResetManualCacheWrite()
	_u.mutation.SetManualCacheWrite(v)
	return _u
}

// SetNillableManualCacheWrite sets the "manual_cache_write" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableManualCacheWrite(v *float64) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetManualCacheWrite(*v)
	}
	return _u
}

// AddManualCacheWrite adds value to the "manual_cache_write" field.
func (_u *ModelPriceOverrideUpdateOne) AddManualCacheWrite(v float64) *ModelPriceOverrideUpdateOne {
	_u.mutation.AddManualCacheWrite(v)
	return _u
}

// ClearManualCacheWrite clears the value of the "manual_cache_write" field.
func (_u *ModelPriceOverrideUpdateOne) ClearManualCacheWrite() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearManualCacheWrite()
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPriceOverrideUpdateOne) SetNote(v string) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableNote(v *string) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ModelPriceOverrideUpdateOne) ClearNote() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ModelPriceOverrideUpdateOne) SetUpdatedBy(v int64) *ModelPriceOverrideUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableUpdatedBy(v *int64) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ModelPriceOverrideUpdateOne) AddUpdatedBy(v int64) *ModelPriceOverrideUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ModelPriceOverrideUpdateOne) ClearUpdatedBy() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ModelPriceOverrideUpdateOne) SetCreatedAt(v time.Time) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableCreatedAt(v *time.Time) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPriceOverrideUpdateOne) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelPriceOverrideMutation object of the builder.
func (_u *ModelPriceOverrideUpdateOne) Mutation() *ModelPriceOverrideMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPriceOverrideUpdate builder.
func (_u *ModelPriceOverrideUpdateOne) Where(ps ...predicate.ModelPriceOverride) *ModelPriceOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPriceOverrideUpdateOne) Select(field string, fields ...string) *ModelPriceOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPriceOverride entity.
func (_u *ModelPriceOverrideUpdateOne) Save(ctx context.Context) (*ModelPriceOverride, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdateOne) SaveX(ctx context.Context) *ModelPriceOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPriceOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPriceOverrideUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpriceoverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPriceOverrideUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelpriceoverride.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PinnedProviderTag(); ok {
		if err := modelpriceoverride.PinnedProviderTagValidator(v); err != nil {
			return &ValidationError{Name: "pinned_provider_tag", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.pinned_provider_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := modelpriceoverride.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.note": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPriceOverrideUpdateOne) sqlSave(ctx context.Context) (_node *ModelPriceOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpriceoverride.Table, modelpriceoverride.Columns, sqlgraph.NewFieldSpec(modelpriceoverride.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPriceOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpriceoverride.FieldID)
		for _, f := range fields {
			if !modelpriceoverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpriceoverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelpriceoverride.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PinnedProviderTag(); ok {
		_spec.SetField(modelpriceoverride.FieldPinnedProviderTag, field.TypeString, value)
	}
	if _u.mutation.PinnedProviderTagCleared() {
		_spec.ClearField(modelpriceoverride.FieldPinnedProviderTag, field.TypeString)
	}
	if value, ok := _u.mutation.ManualInput(); ok {
		_spec.SetField(modelpriceoverride.FieldManualInput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualInput(); ok {
		_spec.AddField(modelpriceoverride.FieldManualInput, field.TypeFloat64, value)
	}
	if _u.mutation.ManualInputCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualInput, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualOutput(); ok {
		_spec.SetField(modelpriceoverride.FieldManualOutput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualOutput(); ok {
		_spec.AddField(modelpriceoverride.FieldManualOutput, field.TypeFloat64, value)
	}
	if _u.mutation.ManualOutputCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualOutput, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualCacheRead(); ok {
		_spec.SetField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualCacheRead(); ok {
		_spec.AddField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64, value)
	}
	if _u.mutation.ManualCacheReadCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualCacheWrite(); ok {
		_spec.SetField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualCacheWrite(); ok {
		_spec.AddField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64, value)
	}
	if _u.mutation.ManualCacheWriteCleared() {
		_spec.ClearField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpriceoverride.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(modelpriceoverride.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelPriceOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpriceoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
