// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/telagod/subme/ent/modelpriceoverride"
)

// ModelPriceOverride is the model entity for the ModelPriceOverride schema.
type ModelPriceOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// PinnedProviderTag holds the value of the "pinned_provider_tag" field.
	PinnedProviderTag string `json:"pinned_provider_tag,omitempty"`
	// ManualInput holds the value of the "manual_input" field.
	ManualInput *float64 `json:"manual_input,omitempty"`
	// ManualOutput holds the value of the "manual_output" field.
	ManualOutput *float64 `json:"manual_output,omitempty"`
	// ManualCacheRead holds the value of the "manual_cache_read" field.
	ManualCacheRead *float64 `json:"manual_cache_read,omitempty"`
	// ManualCacheWrite holds the value of the "manual_cache_write" field.
	ManualCacheWrite *float64 `json:"manual_cache_write,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelPriceOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelpriceoverride.FieldManualInput, modelpriceoverride.FieldManualOutput, modelpriceoverride.FieldManualCacheRead, modelpriceoverride.FieldManualCacheWrite:
			values[i] = new(sql.NullFloat64)
		case modelpriceoverride.FieldID, modelpriceoverride.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case modelpriceoverride.FieldModelID, modelpriceoverride.FieldPinnedProviderTag, modelpriceoverride.FieldNote:
			values[i] = new(sql.NullString)
		case modelpriceoverride.FieldCreatedAt, modelpriceoverride.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelPriceOverride fields.
func (_m *ModelPriceOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelpriceoverride.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelpriceoverride.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelpriceoverride.FieldPinnedProviderTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pinned_provider_tag", values[i])
			} else if value.Valid {
				_m.PinnedProviderTag = value.String
			}
		case modelpriceoverride.FieldManualInput:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_input", values[i])
			} else if value.Valid {
				_m.ManualInput = new(float64)
				*_m.ManualInput = value.Float64
			}
		case modelpriceoverride.FieldManualOutput:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_output", values[i])
			} else if value.Valid {
				_m.ManualOutput = new(float64)
				*_m.ManualOutput = value.Float64
			}
		case modelpriceoverride.FieldManualCacheRead:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_cache_read", values[i])
			} else if value.Valid {
				_m.ManualCacheRead = new(float64)
				*_m.ManualCacheRead = value.Float64
			}
		case modelpriceoverride.FieldManualCacheWrite:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_cache_write", values[i])
			} else if value.Valid {
				_m.ManualCacheWrite = new(float64)
				*_m.ManualCacheWrite = value.Float64
			}
		case modelpriceoverride.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case modelpriceoverride.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case modelpriceoverride.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelpriceoverride.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelPriceOverride.
// This includes values selected through modifiers, order, etc.
func (_m *ModelPriceOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelPriceOverride.
// Note that you need to call ModelPriceOverride.Unwrap() before calling this method if this ModelPriceOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelPriceOverride) Update() *ModelPriceOverrideUpdateOne {
	return NewModelPriceOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelPriceOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelPriceOverride) Unwrap() *ModelPriceOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelPriceOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelPriceOverride) String() string {
	var builder strings.Builder
	builder.WriteString("ModelPriceOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("pinned_provider_tag=")
	builder.WriteString(_m.PinnedProviderTag)
	builder.WriteString(", ")
	if v := _m.ManualInput; v != nil {
		builder.WriteString("manual_input=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ManualOutput; v != nil {
		builder.WriteString("manual_output=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ManualCacheRead; v != nil {
		builder.WriteString("manual_cache_read=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ManualCacheWrite; v != nil {
		builder.WriteString("manual_cache_write=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelPriceOverrides is a parsable slice of ModelPriceOverride.
type ModelPriceOverrides []*ModelPriceOverride
