// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/telagod/subme/ent/modelpriceoverride"
)

// ModelPriceOverrideCreate is the builder for creating a ModelPriceOverride entity.
type ModelPriceOverrideCreate struct {
	config
	mutation *ModelPriceOverrideMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelID sets the "model_id" field.
func (_c *ModelPriceOverrideCreate) SetModelID(v string) *ModelPriceOverrideCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetPinnedProviderTag sets the "pinned_provider_tag" field.
func (_c *ModelPriceOverrideCreate) SetPinnedProviderTag(v string) *ModelPriceOverrideCreate {
	_c.mutation.SetPinnedProviderTag(v)
	return _c
}

// SetNillablePinnedProviderTag sets the "pinned_provider_tag" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillablePinnedProviderTag(v *string) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetPinnedProviderTag(*v)
	}
	return _c
}

// SetManualInput sets the "manual_input" field.
func (_c *ModelPriceOverrideCreate) SetManualInput(v float64) *ModelPriceOverrideCreate {
	_c.mutation.SetManualInput(v)
	return _c
}

// SetNillableManualInput sets the "manual_input" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableManualInput(v *float64) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetManualInput(*v)
	}
	return _c
}

// SetManualOutput sets the "manual_output" field.
func (_c *ModelPriceOverrideCreate) SetManualOutput(v float64) *ModelPriceOverrideCreate {
	_c.mutation.SetManualOutput(v)
	return _c
}

// SetNillableManualOutput sets the "manual_output" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableManualOutput(v *float64) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetManualOutput(*v)
	}
	return _c
}

// SetManualCacheRead sets the "manual_cache_read" field.
func (_c *ModelPriceOverrideCreate) SetManualCacheRead(v float64) *ModelPriceOverrideCreate {
	_c.mutation.SetManualCacheRead(v)
	return _c
}

// SetNillableManualCacheRead sets the "manual_cache_read" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableManualCacheRead(v *float64) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetManualCacheRead(*v)
	}
	return _c
}

// SetManualCacheWrite sets the "manual_cache_write" field.
func (_c *ModelPriceOverrideCreate) SetManualCacheWrite(v float64) *ModelPriceOverrideCreate {
	_c.mutation.SetManualCacheWrite(v)
	return _c
}

// SetNillableManualCacheWrite sets the "manual_cache_write" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableManualCacheWrite(v *float64) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetManualCacheWrite(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ModelPriceOverrideCreate) SetNote(v string) *ModelPriceOverrideCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableNote(v *string) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ModelPriceOverrideCreate) SetUpdatedBy(v int64) *ModelPriceOverrideCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableUpdatedBy(v *int64) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelPriceOverrideCreate) SetCreatedAt(v time.Time) *ModelPriceOverrideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableCreatedAt(v *time.Time) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelPriceOverrideCreate) SetUpdatedAt(v time.Time) *ModelPriceOverrideCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableUpdatedAt(v *time.Time) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ModelPriceOverrideMutation object of the builder.
func (_c *ModelPriceOverrideCreate) Mutation() *ModelPriceOverrideMutation {
	return _c.mutation
}

// Save creates the ModelPriceOverride in the database.
func (_c *ModelPriceOverrideCreate) Save(ctx context.Context) (*ModelPriceOverride, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelPriceOverrideCreate) SaveX(ctx context.Context) *ModelPriceOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPriceOverrideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPriceOverrideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelPriceOverrideCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelpriceoverride.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelpriceoverride.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelPriceOverrideCreate) check() error {
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "ModelPriceOverride.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := modelpriceoverride.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.model_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PinnedProviderTag(); ok {
		if err := modelpriceoverride.PinnedProviderTagValidator(v); err != nil {
			return &ValidationError{Name: "pinned_provider_tag", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.pinned_provider_tag": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := modelpriceoverride.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelPriceOverride.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelPriceOverride.updated_at"`)}
	}
	return nil
}

func (_c *ModelPriceOverrideCreate) sqlSave(ctx context.Context) (*ModelPriceOverride, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelPriceOverrideCreate) createSpec() (*ModelPriceOverride, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelPriceOverride{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelpriceoverride.Table, sqlgraph.NewFieldSpec(modelpriceoverride.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(modelpriceoverride.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.PinnedProviderTag(); ok {
		_spec.SetField(modelpriceoverride.FieldPinnedProviderTag, field.TypeString, value)
		_node.PinnedProviderTag = value
	}
	if value, ok := _c.mutation.ManualInput(); ok {
		_spec.SetField(modelpriceoverride.FieldManualInput, field.TypeFloat64, value)
		_node.ManualInput = &value
	}
	if value, ok := _c.mutation.ManualOutput(); ok {
		_spec.SetField(modelpriceoverride.FieldManualOutput, field.TypeFloat64, value)
		_node.ManualOutput = &value
	}
	if value, ok := _c.mutation.ManualCacheRead(); ok {
		_spec.SetField(modelpriceoverride.FieldManualCacheRead, field.TypeFloat64, value)
		_node.ManualCacheRead = &value
	}
	if value, ok := _c.mutation.ManualCacheWrite(); ok {
		_spec.SetField(modelpriceoverride.FieldManualCacheWrite, field.TypeFloat64, value)
		_node.ManualCacheWrite = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(modelpriceoverride.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelPriceOverride.Create().
//		SetModelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelPriceOverrideUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreate) OnConflict(opts ...sql.ConflictOption) *ModelPriceOverrideUpsertOne {
	_c.conflict = opts
	return &ModelPriceOverrideUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreate) OnConflictColumns(columns ...string) *ModelPriceOverrideUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelPriceOverrideUpsertOne{
		create: _c,
	}
}

type (
	// ModelPriceOverrideUpsertOne is the builder for "upsert"-ing
	//  one ModelPriceOverride node.
	ModelPriceOverrideUpsertOne struct {
		create *ModelPriceOverrideCreate
	}

	// ModelPriceOverrideUpsert is the "OnConflict" setter.
	ModelPriceOverrideUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelID sets the "model_id" field.
func (u *ModelPriceOverrideUpsert) SetModelID(v string) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateModelID() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldModelID)
	return u
}

// SetPinnedProviderTag sets the "pinned_provider_tag" field.
func (u *ModelPriceOverrideUpsert) SetPinnedProviderTag(v string) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldPinnedProviderTag, v)
	return u
}

// UpdatePinnedProviderTag sets the "pinned_provider_tag" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdatePinnedProviderTag() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldPinnedProviderTag)
	return u
}

// ClearPinnedProviderTag clears the value of the "pinned_provider_tag" field.
func (u *ModelPriceOverrideUpsert) ClearPinnedProviderTag() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldPinnedProviderTag)
	return u
}

// SetManualInput sets the "manual_input" field.
func (u *ModelPriceOverrideUpsert) SetManualInput(v float64) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldManualInput, v)
	return u
}

// UpdateManualInput sets the "manual_input" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateManualInput() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldManualInput)
	return u
}

// AddManualInput adds v to the "manual_input" field.
func (u *ModelPriceOverrideUpsert) AddManualInput(v float64) *ModelPriceOverrideUpsert {
	u.Add(modelpriceoverride.FieldManualInput, v)
	return u
}

// ClearManualInput clears the value of the "manual_input" field.
func (u *ModelPriceOverrideUpsert) ClearManualInput() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldManualInput)
	return u
}

// SetManualOutput sets the "manual_output" field.
func (u *ModelPriceOverrideUpsert) SetManualOutput(v float64) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldManualOutput, v)
	return u
}

// UpdateManualOutput sets the "manual_output" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateManualOutput() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldManualOutput)
	return u
}

// AddManualOutput adds v to the "manual_output" field.
func (u *ModelPriceOverrideUpsert) AddManualOutput(v float64) *ModelPriceOverrideUpsert {
	u.Add(modelpriceoverride.FieldManualOutput, v)
	return u
}

// ClearManualOutput clears the value of the "manual_output" field.
func (u *ModelPriceOverrideUpsert) ClearManualOutput() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldManualOutput)
	return u
}

// SetManualCacheRead sets the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsert) SetManualCacheRead(v float64) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldManualCacheRead, v)
	return u
}

// UpdateManualCacheRead sets the "manual_cache_read" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateManualCacheRead() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldManualCacheRead)
	return u
}

// AddManualCacheRead adds v to the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsert) AddManualCacheRead(v float64) *ModelPriceOverrideUpsert {
	u.Add(modelpriceoverride.FieldManualCacheRead, v)
	return u
}

// ClearManualCacheRead clears the value of the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsert) ClearManualCacheRead() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldManualCacheRead)
	return u
}

// SetManualCacheWrite sets the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsert) SetManualCacheWrite(v float64) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldManualCacheWrite, v)
	return u
}

// UpdateManualCacheWrite sets the "manual_cache_write" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateManualCacheWrite() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldManualCacheWrite)
	return u
}

// AddManualCacheWrite adds v to the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsert) AddManualCacheWrite(v float64) *ModelPriceOverrideUpsert {
	u.Add(modelpriceoverride.FieldManualCacheWrite, v)
	return u
}

// ClearManualCacheWrite clears the value of the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsert) ClearManualCacheWrite() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldManualCacheWrite)
	return u
}

// SetNote sets the "note" field.
func (u *ModelPriceOverrideUpsert) SetNote(v string) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateNote() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *ModelPriceOverrideUpsert) ClearNote() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldNote)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ModelPriceOverrideUpsert) SetUpdatedBy(v int64) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateUpdatedBy() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ModelPriceOverrideUpsert) AddUpdatedBy(v int64) *ModelPriceOverrideUpsert {
	u.Add(modelpriceoverride.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ModelPriceOverrideUpsert) ClearUpdatedBy() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldUpdatedBy)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ModelPriceOverrideUpsert) SetCreatedAt(v time.Time) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateCreatedAt() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPriceOverrideUpsert) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateUpdatedAt() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelPriceOverrideUpsertOne) UpdateNewValues() *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelPriceOverrideUpsertOne) Ignore() *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelPriceOverrideUpsertOne) DoNothing() *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelPriceOverrideCreate.OnConflict
// documentation for more info.
func (u *ModelPriceOverrideUpsertOne) Update(set func(*ModelPriceOverrideUpsert)) *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelPriceOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *ModelPriceOverrideUpsertOne) SetModelID(v string) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateModelID() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateModelID()
	})
}

// SetPinnedProviderTag sets the "pinned_provider_tag" field.
func (u *ModelPriceOverrideUpsertOne) SetPinnedProviderTag(v string) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetPinnedProviderTag(v)
	})
}

// UpdatePinnedProviderTag sets the "pinned_provider_tag" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdatePinnedProviderTag() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdatePinnedProviderTag()
	})
}

// ClearPinnedProviderTag clears the value of the "pinned_provider_tag" field.
func (u *ModelPriceOverrideUpsertOne) ClearPinnedProviderTag() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearPinnedProviderTag()
	})
}

// SetManualInput sets the "manual_input" field.
func (u *ModelPriceOverrideUpsertOne) SetManualInput(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualInput(v)
	})
}

// AddManualInput adds v to the "manual_input" field.
func (u *ModelPriceOverrideUpsertOne) AddManualInput(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualInput(v)
	})
}

// UpdateManualInput sets the "manual_input" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateManualInput() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualInput()
	})
}

// ClearManualInput clears the value of the "manual_input" field.
func (u *ModelPriceOverrideUpsertOne) ClearManualInput() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualInput()
	})
}

// SetManualOutput sets the "manual_output" field.
func (u *ModelPriceOverrideUpsertOne) SetManualOutput(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualOutput(v)
	})
}

// AddManualOutput adds v to the "manual_output" field.
func (u *ModelPriceOverrideUpsertOne) AddManualOutput(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualOutput(v)
	})
}

// UpdateManualOutput sets the "manual_output" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateManualOutput() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualOutput()
	})
}

// ClearManualOutput clears the value of the "manual_output" field.
func (u *ModelPriceOverrideUpsertOne) ClearManualOutput() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualOutput()
	})
}

// SetManualCacheRead sets the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsertOne) SetManualCacheRead(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualCacheRead(v)
	})
}

// AddManualCacheRead adds v to the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsertOne) AddManualCacheRead(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualCacheRead(v)
	})
}

// UpdateManualCacheRead sets the "manual_cache_read" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateManualCacheRead() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualCacheRead()
	})
}

// ClearManualCacheRead clears the value of the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsertOne) ClearManualCacheRead() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualCacheRead()
	})
}

// SetManualCacheWrite sets the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsertOne) SetManualCacheWrite(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualCacheWrite(v)
	})
}

// AddManualCacheWrite adds v to the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsertOne) AddManualCacheWrite(v float64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualCacheWrite(v)
	})
}

// UpdateManualCacheWrite sets the "manual_cache_write" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateManualCacheWrite() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualCacheWrite()
	})
}

// ClearManualCacheWrite clears the value of the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsertOne) ClearManualCacheWrite() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualCacheWrite()
	})
}

// SetNote sets the "note" field.
func (u *ModelPriceOverrideUpsertOne) SetNote(v string) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateNote() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ModelPriceOverrideUpsertOne) ClearNote() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearNote()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ModelPriceOverrideUpsertOne) SetUpdatedBy(v int64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ModelPriceOverrideUpsertOne) AddUpdatedBy(v int64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateUpdatedBy() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ModelPriceOverrideUpsertOne) ClearUpdatedBy() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ModelPriceOverrideUpsertOne) SetCreatedAt(v time.Time) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateCreatedAt() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPriceOverrideUpsertOne) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateUpdatedAt() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelPriceOverrideUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelPriceOverrideCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelPriceOverrideUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelPriceOverrideUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelPriceOverrideUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelPriceOverrideCreateBulk is the builder for creating many ModelPriceOverride entities in bulk.
type ModelPriceOverrideCreateBulk struct {
	config
	err      error
	builders []*ModelPriceOverrideCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelPriceOverride entities in the database.
func (_c *ModelPriceOverrideCreateBulk) Save(ctx context.Context) ([]*ModelPriceOverride, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelPriceOverride, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelPriceOverrideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelPriceOverrideCreateBulk) SaveX(ctx context.Context) []*ModelPriceOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPriceOverrideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPriceOverrideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelPriceOverride.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelPriceOverrideUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelPriceOverrideUpsertBulk {
	_c.conflict = opts
	return &ModelPriceOverrideUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreateBulk) OnConflictColumns(columns ...string) *ModelPriceOverrideUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelPriceOverrideUpsertBulk{
		create: _c,
	}
}

// ModelPriceOverrideUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelPriceOverride nodes.
type ModelPriceOverrideUpsertBulk struct {
	create *ModelPriceOverrideCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelPriceOverrideUpsertBulk) UpdateNewValues() *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelPriceOverrideUpsertBulk) Ignore() *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelPriceOverrideUpsertBulk) DoNothing() *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelPriceOverrideCreateBulk.OnConflict
// documentation for more info.
func (u *ModelPriceOverrideUpsertBulk) Update(set func(*ModelPriceOverrideUpsert)) *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelPriceOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *ModelPriceOverrideUpsertBulk) SetModelID(v string) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateModelID() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateModelID()
	})
}

// SetPinnedProviderTag sets the "pinned_provider_tag" field.
func (u *ModelPriceOverrideUpsertBulk) SetPinnedProviderTag(v string) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetPinnedProviderTag(v)
	})
}

// UpdatePinnedProviderTag sets the "pinned_provider_tag" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdatePinnedProviderTag() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdatePinnedProviderTag()
	})
}

// ClearPinnedProviderTag clears the value of the "pinned_provider_tag" field.
func (u *ModelPriceOverrideUpsertBulk) ClearPinnedProviderTag() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearPinnedProviderTag()
	})
}

// SetManualInput sets the "manual_input" field.
func (u *ModelPriceOverrideUpsertBulk) SetManualInput(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualInput(v)
	})
}

// AddManualInput adds v to the "manual_input" field.
func (u *ModelPriceOverrideUpsertBulk) AddManualInput(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualInput(v)
	})
}

// UpdateManualInput sets the "manual_input" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateManualInput() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualInput()
	})
}

// ClearManualInput clears the value of the "manual_input" field.
func (u *ModelPriceOverrideUpsertBulk) ClearManualInput() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualInput()
	})
}

// SetManualOutput sets the "manual_output" field.
func (u *ModelPriceOverrideUpsertBulk) SetManualOutput(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualOutput(v)
	})
}

// AddManualOutput adds v to the "manual_output" field.
func (u *ModelPriceOverrideUpsertBulk) AddManualOutput(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualOutput(v)
	})
}

// UpdateManualOutput sets the "manual_output" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateManualOutput() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualOutput()
	})
}

// ClearManualOutput clears the value of the "manual_output" field.
func (u *ModelPriceOverrideUpsertBulk) ClearManualOutput() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualOutput()
	})
}

// SetManualCacheRead sets the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsertBulk) SetManualCacheRead(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualCacheRead(v)
	})
}

// AddManualCacheRead adds v to the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsertBulk) AddManualCacheRead(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualCacheRead(v)
	})
}

// UpdateManualCacheRead sets the "manual_cache_read" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateManualCacheRead() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualCacheRead()
	})
}

// ClearManualCacheRead clears the value of the "manual_cache_read" field.
func (u *ModelPriceOverrideUpsertBulk) ClearManualCacheRead() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualCacheRead()
	})
}

// SetManualCacheWrite sets the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsertBulk) SetManualCacheWrite(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetManualCacheWrite(v)
	})
}

// AddManualCacheWrite adds v to the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsertBulk) AddManualCacheWrite(v float64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddManualCacheWrite(v)
	})
}

// UpdateManualCacheWrite sets the "manual_cache_write" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateManualCacheWrite() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateManualCacheWrite()
	})
}

// ClearManualCacheWrite clears the value of the "manual_cache_write" field.
func (u *ModelPriceOverrideUpsertBulk) ClearManualCacheWrite() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearManualCacheWrite()
	})
}

// SetNote sets the "note" field.
func (u *ModelPriceOverrideUpsertBulk) SetNote(v string) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateNote() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ModelPriceOverrideUpsertBulk) ClearNote() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearNote()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ModelPriceOverrideUpsertBulk) SetUpdatedBy(v int64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ModelPriceOverrideUpsertBulk) AddUpdatedBy(v int64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateUpdatedBy() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ModelPriceOverrideUpsertBulk) ClearUpdatedBy() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ModelPriceOverrideUpsertBulk) SetCreatedAt(v time.Time) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateCreatedAt() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPriceOverrideUpsertBulk) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateUpdatedAt() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelPriceOverrideUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelPriceOverrideCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelPriceOverrideCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelPriceOverrideUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
