// Code generated by ent, DO NOT EDIT.

package modelpriceoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelpriceoverride type in the database.
	Label = "model_price_override"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldPinnedProviderTag holds the string denoting the pinned_provider_tag field in the database.
	FieldPinnedProviderTag = "pinned_provider_tag"
	// FieldManualInput holds the string denoting the manual_input field in the database.
	FieldManualInput = "manual_input"
	// FieldManualOutput holds the string denoting the manual_output field in the database.
	FieldManualOutput = "manual_output"
	// FieldManualCacheRead holds the string denoting the manual_cache_read field in the database.
	FieldManualCacheRead = "manual_cache_read"
	// FieldManualCacheWrite holds the string denoting the manual_cache_write field in the database.
	FieldManualCacheWrite = "manual_cache_write"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelpriceoverride in the database.
	Table = "model_price_overrides"
)

// Columns holds all SQL columns for modelpriceoverride fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldPinnedProviderTag,
	FieldManualInput,
	FieldManualOutput,
	FieldManualCacheRead,
	FieldManualCacheWrite,
	FieldNote,
	FieldUpdatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// PinnedProviderTagValidator is a validator for the "pinned_provider_tag" field. It is called by the builders before save.
	PinnedProviderTagValidator func(string) error
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelPriceOverride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByPinnedProviderTag orders the results by the pinned_provider_tag field.
func ByPinnedProviderTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinnedProviderTag, opts...).ToFunc()
}

// ByManualInput orders the results by the manual_input field.
func ByManualInput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualInput, opts...).ToFunc()
}

// ByManualOutput orders the results by the manual_output field.
func ByManualOutput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualOutput, opts...).ToFunc()
}

// ByManualCacheRead orders the results by the manual_cache_read field.
func ByManualCacheRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualCacheRead, opts...).ToFunc()
}

// ByManualCacheWrite orders the results by the manual_cache_write field.
func ByManualCacheWrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualCacheWrite, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
