// Code generated by ent, DO NOT EDIT.

package modelpriceoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/telagod/subme/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldID, id))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldModelID, v))
}

// PinnedProviderTag applies equality check predicate on the "pinned_provider_tag" field. It's identical to PinnedProviderTagEQ.
func PinnedProviderTag(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldPinnedProviderTag, v))
}

// ManualInput applies equality check predicate on the "manual_input" field. It's identical to ManualInputEQ.
func ManualInput(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualInput, v))
}

// ManualOutput applies equality check predicate on the "manual_output" field. It's identical to ManualOutputEQ.
func ManualOutput(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualOutput, v))
}

// ManualCacheRead applies equality check predicate on the "manual_cache_read" field. It's identical to ManualCacheReadEQ.
func ManualCacheRead(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualCacheRead, v))
}

// ManualCacheWrite applies equality check predicate on the "manual_cache_write" field. It's identical to ManualCacheWriteEQ.
func ManualCacheWrite(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualCacheWrite, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldNote, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldContainsFold(FieldModelID, v))
}

// PinnedProviderTagEQ applies the EQ predicate on the "pinned_provider_tag" field.
func PinnedProviderTagEQ(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldPinnedProviderTag, v))
}

// PinnedProviderTagNEQ applies the NEQ predicate on the "pinned_provider_tag" field.
func PinnedProviderTagNEQ(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldPinnedProviderTag, v))
}

// PinnedProviderTagIn applies the In predicate on the "pinned_provider_tag" field.
func PinnedProviderTagIn(vs ...string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldPinnedProviderTag, vs...))
}

// PinnedProviderTagNotIn applies the NotIn predicate on the "pinned_provider_tag" field.
func PinnedProviderTagNotIn(vs ...string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldPinnedProviderTag, vs...))
}

// PinnedProviderTagGT applies the GT predicate on the "pinned_provider_tag" field.
func PinnedProviderTagGT(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldPinnedProviderTag, v))
}

// PinnedProviderTagGTE applies the GTE predicate on the "pinned_provider_tag" field.
func PinnedProviderTagGTE(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldPinnedProviderTag, v))
}

// PinnedProviderTagLT applies the LT predicate on the "pinned_provider_tag" field.
func PinnedProviderTagLT(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldPinnedProviderTag, v))
}

// PinnedProviderTagLTE applies the LTE predicate on the "pinned_provider_tag" field.
func PinnedProviderTagLTE(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldPinnedProviderTag, v))
}

// PinnedProviderTagContains applies the Contains predicate on the "pinned_provider_tag" field.
func PinnedProviderTagContains(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldContains(FieldPinnedProviderTag, v))
}

// PinnedProviderTagHasPrefix applies the HasPrefix predicate on the "pinned_provider_tag" field.
func PinnedProviderTagHasPrefix(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldHasPrefix(FieldPinnedProviderTag, v))
}

// PinnedProviderTagHasSuffix applies the HasSuffix predicate on the "pinned_provider_tag" field.
func PinnedProviderTagHasSuffix(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldHasSuffix(FieldPinnedProviderTag, v))
}

// PinnedProviderTagIsNil applies the IsNil predicate on the "pinned_provider_tag" field.
func PinnedProviderTagIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldPinnedProviderTag))
}

// PinnedProviderTagNotNil applies the NotNil predicate on the "pinned_provider_tag" field.
func PinnedProviderTagNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldPinnedProviderTag))
}

// PinnedProviderTagEqualFold applies the EqualFold predicate on the "pinned_provider_tag" field.
func PinnedProviderTagEqualFold(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEqualFold(FieldPinnedProviderTag, v))
}

// PinnedProviderTagContainsFold applies the ContainsFold predicate on the "pinned_provider_tag" field.
func PinnedProviderTagContainsFold(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldContainsFold(FieldPinnedProviderTag, v))
}

// ManualInputEQ applies the EQ predicate on the "manual_input" field.
func ManualInputEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualInput, v))
}

// ManualInputNEQ applies the NEQ predicate on the "manual_input" field.
func ManualInputNEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldManualInput, v))
}

// ManualInputIn applies the In predicate on the "manual_input" field.
func ManualInputIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldManualInput, vs...))
}

// ManualInputNotIn applies the NotIn predicate on the "manual_input" field.
func ManualInputNotIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldManualInput, vs...))
}

// ManualInputGT applies the GT predicate on the "manual_input" field.
func ManualInputGT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldManualInput, v))
}

// ManualInputGTE applies the GTE predicate on the "manual_input" field.
func ManualInputGTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldManualInput, v))
}

// ManualInputLT applies the LT predicate on the "manual_input" field.
func ManualInputLT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldManualInput, v))
}

// ManualInputLTE applies the LTE predicate on the "manual_input" field.
func ManualInputLTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldManualInput, v))
}

// ManualInputIsNil applies the IsNil predicate on the "manual_input" field.
func ManualInputIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldManualInput))
}

// ManualInputNotNil applies the NotNil predicate on the "manual_input" field.
func ManualInputNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldManualInput))
}

// ManualOutputEQ applies the EQ predicate on the "manual_output" field.
func ManualOutputEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualOutput, v))
}

// ManualOutputNEQ applies the NEQ predicate on the "manual_output" field.
func ManualOutputNEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldManualOutput, v))
}

// ManualOutputIn applies the In predicate on the "manual_output" field.
func ManualOutputIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldManualOutput, vs...))
}

// ManualOutputNotIn applies the NotIn predicate on the "manual_output" field.
func ManualOutputNotIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldManualOutput, vs...))
}

// ManualOutputGT applies the GT predicate on the "manual_output" field.
func ManualOutputGT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldManualOutput, v))
}

// ManualOutputGTE applies the GTE predicate on the "manual_output" field.
func ManualOutputGTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldManualOutput, v))
}

// ManualOutputLT applies the LT predicate on the "manual_output" field.
func ManualOutputLT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldManualOutput, v))
}

// ManualOutputLTE applies the LTE predicate on the "manual_output" field.
func ManualOutputLTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldManualOutput, v))
}

// ManualOutputIsNil applies the IsNil predicate on the "manual_output" field.
func ManualOutputIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldManualOutput))
}

// ManualOutputNotNil applies the NotNil predicate on the "manual_output" field.
func ManualOutputNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldManualOutput))
}

// ManualCacheReadEQ applies the EQ predicate on the "manual_cache_read" field.
func ManualCacheReadEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualCacheRead, v))
}

// ManualCacheReadNEQ applies the NEQ predicate on the "manual_cache_read" field.
func ManualCacheReadNEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldManualCacheRead, v))
}

// ManualCacheReadIn applies the In predicate on the "manual_cache_read" field.
func ManualCacheReadIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldManualCacheRead, vs...))
}

// ManualCacheReadNotIn applies the NotIn predicate on the "manual_cache_read" field.
func ManualCacheReadNotIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldManualCacheRead, vs...))
}

// ManualCacheReadGT applies the GT predicate on the "manual_cache_read" field.
func ManualCacheReadGT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldManualCacheRead, v))
}

// ManualCacheReadGTE applies the GTE predicate on the "manual_cache_read" field.
func ManualCacheReadGTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldManualCacheRead, v))
}

// ManualCacheReadLT applies the LT predicate on the "manual_cache_read" field.
func ManualCacheReadLT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldManualCacheRead, v))
}

// ManualCacheReadLTE applies the LTE predicate on the "manual_cache_read" field.
func ManualCacheReadLTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldManualCacheRead, v))
}

// ManualCacheReadIsNil applies the IsNil predicate on the "manual_cache_read" field.
func ManualCacheReadIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldManualCacheRead))
}

// ManualCacheReadNotNil applies the NotNil predicate on the "manual_cache_read" field.
func ManualCacheReadNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldManualCacheRead))
}

// ManualCacheWriteEQ applies the EQ predicate on the "manual_cache_write" field.
func ManualCacheWriteEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldManualCacheWrite, v))
}

// ManualCacheWriteNEQ applies the NEQ predicate on the "manual_cache_write" field.
func ManualCacheWriteNEQ(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldManualCacheWrite, v))
}

// ManualCacheWriteIn applies the In predicate on the "manual_cache_write" field.
func ManualCacheWriteIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldManualCacheWrite, vs...))
}

// ManualCacheWriteNotIn applies the NotIn predicate on the "manual_cache_write" field.
func ManualCacheWriteNotIn(vs ...float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldManualCacheWrite, vs...))
}

// ManualCacheWriteGT applies the GT predicate on the "manual_cache_write" field.
func ManualCacheWriteGT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldManualCacheWrite, v))
}

// ManualCacheWriteGTE applies the GTE predicate on the "manual_cache_write" field.
func ManualCacheWriteGTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldManualCacheWrite, v))
}

// ManualCacheWriteLT applies the LT predicate on the "manual_cache_write" field.
func ManualCacheWriteLT(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldManualCacheWrite, v))
}

// ManualCacheWriteLTE applies the LTE predicate on the "manual_cache_write" field.
func ManualCacheWriteLTE(v float64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldManualCacheWrite, v))
}

// ManualCacheWriteIsNil applies the IsNil predicate on the "manual_cache_write" field.
func ManualCacheWriteIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldManualCacheWrite))
}

// ManualCacheWriteNotNil applies the NotNil predicate on the "manual_cache_write" field.
func ManualCacheWriteNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldManualCacheWrite))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldContainsFold(FieldNote, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotNull(FieldUpdatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelPriceOverride) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelPriceOverride) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelPriceOverride) predicate.ModelPriceOverride {
	return predicate.ModelPriceOverride(sql.NotPredicates(p))
}
